jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          sudo chown -R $USER /opt/theos

      - name: Install ldid (optional)
        run: brew install ldid || true  # 即使失败也继续

      - name: Build
        run: |
          export SDKROOT=$(xcrun --sdk iphoneos --show-sdk-path)
          export CODESIGN=NO   # 强制跳过签名
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoClick.dylib
          path: .theos/obj/*.dylib
